<?php

namespace Mara\Ymanager\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BotChanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotChanRepository extends EntityRepository
{


}
