<?php

namespace Mara\Ymanager\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OauthUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthUserRepository extends EntityRepository
{
}
